### ISSUE TITLE
Contribution to your android-quickform

### ISSUE THREAD

**Issue by edemiguel** [thehung111/android-quickform#1]
Hi "the hung"
My name is Enrique de Miguel and I like your android form generator. I was wondering if you accept contributions to your project. I've got a few ideas and I would like to develop some of them.
I hope to hear from you soon.

Regards
Enrique de Miguel

**Comment by thehung111** [comment]
Hi Enrique,

Thank you for the interest. Unfortunately, I do not have the time and am not planning to maintain this project currently/actively. I think you can just fork the project and add the extra features as you see fit :)

There are many changes in the Android world e.g. gradle build systems from the time I wrote this library. Feel free to add/modify the project :)
